package cn.huan.kindergarten.dto;

import java.util.Date;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "kg_assessment_activity_user_upload")
public class KgAssessmentActivityUserUpload extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_UPLOAD_USER_ID = "uploadUserId";
     public static final String FIELD_ASSESSMENT_ACTIVITY_ID = "assessmentActivityId";
     public static final String FIELD_FILE_PATH = "filePath";
     public static final String FILENAME = "fileName";

     @Id
     @GeneratedValue
     private Long id;

     @Length(max = 19)
     private Long uploadUserId;

     @Length(max = 19)
     private Long progressId;
     
     @Length(max = 240)
     private String fileName;

     @Length(max = 240)
     private String filePath;
     
     
     private Date createdate;

     public Date getCreatedate() {
 		return createdate;
 	}

 	public void setCreatedate(Date createdate) {
 		this.createdate = createdate;
 	}
   

	public Long getProgressId() {
		return progressId;
	}

	public void setProgressId(Long progressId) {
		this.progressId = progressId;
	}

	public void setUploadUserId(Long uploadUserId){
         this.uploadUserId = uploadUserId;
     }

     public Long getUploadUserId(){
         return uploadUserId;
     }

   

     public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setFilePath(String filePath){
         this.filePath = filePath;
     }

     public String getFilePath(){
         return filePath;
     }

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
     
     

     }
