package cn.huan.kindergarten.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_canton")
public class KgCanton extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_CANTON_NAME = "cantonName";


     @Id
     @GeneratedValue
     private String id;

     @NotEmpty
     @Length(max = 45)
     private String cantonname;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

	public String getCantonname() {
		return cantonname;
	}

	public void setCantonname(String cantonname) {
		this.cantonname = cantonname;
	}

   

     }
