package cn.huan.kindergarten.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_config")
public class KgConfig extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_SYSNAME = "sysname";
     public static final String FIELD_SYSKEY = "syskey";
     public static final String FIELD_SYSVALUE = "sysvalue";


     @Id
     @GeneratedValue
     private Long id;

     @NotEmpty
     @Length(max = 40)
     private String sysname;

     @Length(max = 40)
     private String syskey;

     @Length(max = 200)
     private String sysvalue;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setSysname(String sysname){
         this.sysname = sysname;
     }

     public String getSysname(){
         return sysname;
     }

     public void setSyskey(String syskey){
         this.syskey = syskey;
     }

     public String getSyskey(){
         return syskey;
     }

     public void setSysvalue(String sysvalue){
         this.sysvalue = sysvalue;
     }

     public String getSysvalue(){
         return sysvalue;
     }

     }
