package cn.huan.kindergarten.dto;

import java.util.Date;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_download")
public class KgDownload extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_FILE_TITLE = "fileTitle";
     public static final String FIELD_FILE_PATH = "filePath";
     public static final String FIELD_SUMMARY = "summary";
     public static final String CREATEDATE = "createDate";


     @Id
     @GeneratedValue
     private String id;

     @NotEmpty
     @Length(max = 200)
     private String fileTitle;

     @NotEmpty
     @Length(max = 200)
     private String filePath;

     @Length(max = 200)
     private String summary;
     
     @Length(max=200)
     private String password;
     

     private Date createdate;

     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setFileTitle(String fileTitle){
         this.fileTitle = fileTitle;
     }

     public String getFileTitle(){
         return fileTitle;
     }

     public void setFilePath(String filePath){
         this.filePath = filePath;
     }

     public String getFilePath(){
         return filePath;
     }

     public void setSummary(String summary){
         this.summary = summary;
     }

     public String getSummary(){
         return summary;
     }

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
     
     

     }
