package cn.huan.kindergarten.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "kg_introduction")
public class KgIntroduction extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_INTRODUCTION = "introduction";


     @Id
     @GeneratedValue
     private Long id;

     @Length(max = 65535)
     private String introduction;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setIntroduction(String introduction){
         this.introduction = introduction;
     }

     public String getIntroduction(){
         return introduction;
     }

     }
