package cn.huan.kindergarten.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_member_units")
public class KgMemberUnits extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_MEMBERNO = "memberno";
     public static final String FIELD_CANTON = "canton";
     public static final String FIELD_KINDERGARTENNAME = "kindergartenname";
     public static final String FIELD_KINDERGARTENSITE = "kindergartensite";
     public static final String FIELD_ZIPCODE = "zipcode";
     public static final String FIELD_TELPHONE = "telphone";
     public static final String FIELD_LEVEL = "level";
     public static final String FIELD_NATURE = "nature";
     public static final String FIELD_ADMISSIONTIME = "admissiontime";
     public static final String FIELD_TYPEID = "typeid";


     @Id
     @GeneratedValue
     private String id;

     @NotEmpty
     @Length(max = 45)
     private String memberno;

     @NotNull
     private Long canton;

     @NotEmpty
     @Length(max = 45)
     private String kindergartenname;

     @NotEmpty
     @Length(max = 45)
     private String kindergartensite;

     @NotEmpty
     @Length(max = 45)
     private String zipcode;

     @NotEmpty
     @Length(max = 45)
     private String telphone;

     @NotEmpty
     @Length(max = 45)
     private String level;

     @NotEmpty
     @Length(max = 45)
     private String nature;

     private Date admissiontime;

     @Length(max = 20)
     private String typeid;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setMemberno(String memberno){
         this.memberno = memberno;
     }

     public String getMemberno(){
         return memberno;
     }

     public void setCanton(Long canton){
         this.canton = canton;
     }

     public Long getCanton(){
         return canton;
     }

     public void setKindergartenname(String kindergartenname){
         this.kindergartenname = kindergartenname;
     }

     public String getKindergartenname(){
         return kindergartenname;
     }

     public void setKindergartensite(String kindergartensite){
         this.kindergartensite = kindergartensite;
     }

     public String getKindergartensite(){
         return kindergartensite;
     }

     public void setZipcode(String zipcode){
         this.zipcode = zipcode;
     }

     public String getZipcode(){
         return zipcode;
     }

     public void setTelphone(String telphone){
         this.telphone = telphone;
     }

     public String getTelphone(){
         return telphone;
     }

     public void setLevel(String level){
         this.level = level;
     }

     public String getLevel(){
         return level;
     }

     public void setNature(String nature){
         this.nature = nature;
     }

     public String getNature(){
         return nature;
     }

     public void setAdmissiontime(Date admissiontime){
         this.admissiontime = admissiontime;
     }

     public Date getAdmissiontime(){
         return admissiontime;
     }

     public void setTypeid(String typeid){
         this.typeid = typeid;
     }

     public String getTypeid(){
         return typeid;
     }

     }
