package cn.huan.kindergarten.dto;

import java.util.List;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "kg_newstype")
public class KgNewstype extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_TYPENAME = "typename";


     @Id
     @GeneratedValue
     private Long id;

     @NotEmpty
     @Length(max = 45)
     private String typename;
     
     private Boolean showindex;
     
     private String entranceimagepath;
     
     private Boolean showentrance;
     
     @Transient
     private Integer count ;
     @Transient
     private List<KgNews> newsList;
     
     


     public List<KgNews> getNewsList() {
		return newsList;
	}

	public void setNewsList(List<KgNews> newsList) {
		this.newsList = newsList;
	}

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTypename(String typename){
         this.typename = typename;
     }

     public String getTypename(){
         return typename;
     }

	public Boolean getShowindex() {
		return showindex;
	}

	public void setShowindex(Boolean showindex) {
		this.showindex = showindex;
	}

	

	public String getEntranceimagepath() {
		return entranceimagepath;
	}

	public void setEntranceimagepath(String entranceimagepath) {
		this.entranceimagepath = entranceimagepath;
	}

	public Boolean getShowentrance() {
		return showentrance;
	}

	public void setShowentrance(Boolean showentrance) {
		this.showentrance = showentrance;
	}

	
     
     

     }
