package cn.huan.kindergarten.dto;

import java.util.List;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "kg_newsattribute")
public class KgNewsAttribute extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_ATTRIBUTENAME = "attributename";


     @Id
     @GeneratedValue
     private Long id;

     @NotEmpty
     @Length(max = 45)
     private String attributename;
     
     @Transient
     private List<KgNews> newsList;
     
     @Transient
     private List<KgAssessmentActivity> assessmentActivityList;
     
     


     public List<KgAssessmentActivity> getAssessmentActivityList() {
		return assessmentActivityList;
	}

	public void setAssessmentActivityList(List<KgAssessmentActivity> assessmentActivityList) {
		this.assessmentActivityList = assessmentActivityList;
	}

	public List<KgNews> getNewsList() {
		return newsList;
	}

	public void setNewsList(List<KgNews> newsList) {
		this.newsList = newsList;
	}

	public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setAttributename(String attributename){
         this.attributename = attributename;
     }

     public String getAttributename(){
         return attributename;
     }

     }
