package cn.huan.kindergarten.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_offers")
public class KgOffers extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_PUBLISHUNIT = "publishunit";
     public static final String FIELD_CONTACTPERSON = "contactperson";
     public static final String FIELD_CONTACTTEL = "contacttel";
     public static final String FIELD_SALARY = "salary";
     public static final String FIELD_CONTENT = "content";
     public static final String FIELD_PUBLISHDATE = "publishdate";


     public KgOffers() {
		super();
	}

	public KgOffers(Long id) {
		super();
		this.id = id;
	}

	@Id
     @GeneratedValue
     private Long id;
     
     @NotEmpty
     @Length(max = 45)
     private String title;

     @NotEmpty
     @Length(max = 45)
     private String publishunit;

     @NotEmpty
     @Length(max = 200)
     private String contactperson;

     @Length(max = 20)
     private String contacttel;

     @Length(max = 20)
     private String salary;

     @Length(max = 65535)
     private String content;

     private Date publishdate;


   

     public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public void setPublishunit(String publishunit){
         this.publishunit = publishunit;
     }

     public String getPublishunit(){
         return publishunit;
     }

     public void setContactperson(String contactperson){
         this.contactperson = contactperson;
     }

     public String getContactperson(){
         return contactperson;
     }

     public void setContacttel(String contacttel){
         this.contacttel = contacttel;
     }

     public String getContacttel(){
         return contacttel;
     }

     public void setSalary(String salary){
         this.salary = salary;
     }

     public String getSalary(){
         return salary;
     }

     public void setContent(String content){
         this.content = content;
     }

     public String getContent(){
         return content;
     }

     public void setPublishdate(Date publishdate){
         this.publishdate = publishdate;
     }

     public Date getPublishdate(){
         return publishdate;
     }

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

     
     
     }
