package cn.huan.kindergarten.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "kg_question_answer")
public class KgQuestionAnswer extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_QID = "qid";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_VALUE = "value";
     public static final String FIELD_CHECKCURR = "checkcurr";


     @Id
     @GeneratedValue
     private Long id;

     @NotNull
     private Long qid;

     @Length(max = 200)
     private String name;

     @Length(max = 200)
     private String value;

     private Boolean checkcurr;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setQid(Long qid){
         this.qid = qid;
     }

     public Long getQid(){
         return qid;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setValue(String value){
         this.value = value;
     }

     public String getValue(){
         return value;
     }

     public void setCheckcurr(Boolean checkcurr){
         this.checkcurr = checkcurr;
     }

     public Boolean getCheckcurr(){
         return checkcurr;
     }

     }
