package com.shtyxh.manager.dto;

import java.util.Date;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "kg_assessment_activity_user_progress")
public class KgAssessmentActivityUserProgress extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_ASSESSMENT_ACTIVITY_ID = "assessmentActivityId";
     public static final String FIELD_UPLOAD_USER_ID = "uploadUserId";
     public static final String FIELD_ADMIN_SUGGESTION = "adminSuggestion";
     public static final String FIELD_EXPERT_USER_ID = "expertUserId";
     public static final String FIELD_EXPERT_SUGGESTION = "expertSuggestion";
     public static final String FIELD_STATE = "state";


     @Id
     @GeneratedValue
     private Long id;

     private Long assessmentActivityId;

     private Long uploadUserId;

     @Length(max = 65535)
     private String adminSuggestion;

     private Long expertUserId;

     @Length(max = 65535)
     private String expertSuggestion;
     
     private Date createdate;

     @Length(max = 240)
     private Integer state;
     
     @Transient
     private KgAssessmentActivity kgAssessmentActivity;
     @Transient
     private String assessmentActivityName;
     
     @Transient
     private String uploadUserName;
     
     @Transient
     private String expertUserName;
     


     public KgAssessmentActivity getKgAssessmentActivity() {
		return kgAssessmentActivity;
	}

	public void setKgAssessmentActivity(KgAssessmentActivity kgAssessmentActivity) {
		this.kgAssessmentActivity = kgAssessmentActivity;
	}

	public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setAssessmentActivityId(Long assessmentActivityId){
         this.assessmentActivityId = assessmentActivityId;
     }

     public Long getAssessmentActivityId(){
         return assessmentActivityId;
     }

     public void setUploadUserId(Long uploadUserId){
         this.uploadUserId = uploadUserId;
     }

     public Long getUploadUserId(){
         return uploadUserId;
     }

     public void setAdminSuggestion(String adminSuggestion){
         this.adminSuggestion = adminSuggestion;
     }

     public String getAdminSuggestion(){
         return adminSuggestion;
     }

     public void setExpertUserId(Long expertUserId){
         this.expertUserId = expertUserId;
     }

     public Long getExpertUserId(){
         return expertUserId;
     }

     public void setExpertSuggestion(String expertSuggestion){
         this.expertSuggestion = expertSuggestion;
     }

     public String getExpertSuggestion(){
         return expertSuggestion;
     }

     public void setState(Integer state){
         this.state = state;
     }

     public Integer getState(){
         return state;
     }

	public String getAssessmentActivityName() {
		return assessmentActivityName;
	}

	public void setAssessmentActivityName(String assessmentActivityName) {
		this.assessmentActivityName = assessmentActivityName;
	}

	public String getUploadUserName() {
		return uploadUserName;
	}

	public void setUploadUserName(String uploadUserName) {
		this.uploadUserName = uploadUserName;
	}

	public String getExpertUserName() {
		return expertUserName;
	}

	public void setExpertUserName(String expertUserName) {
		this.expertUserName = expertUserName;
	}

	public Date getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}
     
     

     }
