package com.shtyxh.manager.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_baywindow")
public class KgBaywindow extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_FILE_PATH = "filePath";
     public static final String FIELD_INDEXSHOW = "indexshow";
     public static final String FIELD_URLTYPE = "urltype";
     public static final String FIELD_WEB_URL = "webUrl";
     public static final String FIELD_ACTIVITY_ID = "activityId";
     public static final String FIELD_NEWS_ID = "newsId";


     @Id
     @GeneratedValue
     private String id;

     @NotEmpty
     @Length(max = 200)
     private String filePath;

     @NotEmpty
     @Length(max = 1)
     private String indexshow; ////

     @Length(max = 20)
     private String urltype; //0:weburl , 1:activity ,2 :news

     @Length(max = 200)
     private String webUrl;

     private Long activityId;

     private Long newsId;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setFilePath(String filePath){
         this.filePath = filePath;
     }

     public String getFilePath(){
         return filePath;
     }

     public void setIndexshow(String indexshow){
         this.indexshow = indexshow;
     }

     public String getIndexshow(){
         return indexshow;
     }

     public void setUrltype(String urltype){
         this.urltype = urltype;
     }

     public String getUrltype(){
         return urltype;
     }

     public void setWebUrl(String webUrl){
         this.webUrl = webUrl;
     }

     public String getWebUrl(){
         return webUrl;
     }

     public void setActivityId(Long activityId){
         this.activityId = activityId;
     }

     public Long getActivityId(){
         return activityId;
     }

     public void setNewsId(Long newsId){
         this.newsId = newsId;
     }

     public Long getNewsId(){
         return newsId;
     }

     }
