package com.shtyxh.manager.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_history")
public class KgHistory extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_YEAR = "historyyear";
     public static final String FIELD_CONTENT = "content";


     @Id
     @GeneratedValue
     private String id;

     @NotEmpty
     @Length(max = 45)
     private String historyyear;

     @Length(max = 200)
     private String content;
     
     @Length(max=45)
     private String historytime;
     
     


     public String getHistorytime() {
		return historytime;
	}

	public void setHistorytime(String historytime) {
		this.historytime = historytime;
	}

	public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

   

     public String getHistoryyear() {
		return historyyear;
	}

	public void setHistoryyear(String historyyear) {
		this.historyyear = historyyear;
	}

	public void setContent(String content){
         this.content = content;
     }

     public String getContent(){
         return content;
     }

     }
