package com.shtyxh.manager.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_notice")
public class KgNotice extends BaseDTO {



     @Id
     @GeneratedValue
     private Long id;

     @NotEmpty
     @Length(max = 255)
     private String name;
     
   
     
     private Long sequence;
     
     private Long urltype; //0:weburl,1 :news , 2:activity 

     private String webUrl;

     private Long activityId;

     private Long newsId;


     public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getUrltype() {
		return urltype;
	}

	public void setUrltype(Long urltype) {
		this.urltype = urltype;
	}

	public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

    
     public void setWebUrl(String webUrl){
         this.webUrl = webUrl;
     }

     public String getWebUrl(){
         return webUrl;
     }

     public void setActivityId(Long activityId){
         this.activityId = activityId;
     }

     public Long getActivityId(){
         return activityId;
     }

     public void setNewsId(Long newsId){
         this.newsId = newsId;
     }

     public Long getNewsId(){
         return newsId;
     }

	public Long getSequence() {
		return sequence;
	}

	public void setSequence(Long sequence) {
		this.sequence = sequence;
	}

	
     

     }
