package com.shtyxh.manager.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_offers_type")
public class KgOffersType extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_OFFERTYPENAME = "offertypename";


     @Id
     @GeneratedValue
     private String id;

     @NotEmpty
     @Length(max = 45)
     private String offertypename;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setOffertypename(String offertypename){
         this.offertypename = offertypename;
     }

     public String getOffertypename(){
         return offertypename;
     }

     }
