package com.shtyxh.manager.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.huan.HTed.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "kg_offers")
public class KgOffers extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_PUBLISHUNIT = "publishunit";
     public static final String FIELD_CONTACTPERSON = "contactperson";
     public static final String FIELD_CONTACTTEL = "contacttel";
     public static final String FIELD_SALARY = "salary";
     public static final String FIELD_CONTENT = "content";
     public static final String FIELD_PUBLISHDATE = "publishdate";


     public KgOffers() {
		super();
	}

	public KgOffers(Long id) {
		super();
		this.id = id;
	}

	@Id
     @GeneratedValue
     private Long id;
	
	
	 private Long cantonid;
     
     @NotEmpty
     @Length(max = 100)
     private String unitname;

     private Long unittypeid;
     
     @Length(max = 100)
     private String offertitle;

     private Integer offercount;
     
     private String content;
     
     private String contactperson;
     
     private String contactposition;
     
     private String zipcode;
     
     private String contacttel;
     
     private Long publishuserid;
     
     private Date publishdate;
     @Transient
     private String newsSimpleTitle;
     
     @Transient
     private KgCanton kgcanton;

     @Transient
     private KgUnitType kgUnitType;

     
     
     
	public KgUnitType getKgUnitType() {
		return kgUnitType;
	}

	public void setKgUnitType(KgUnitType kgUnitType) {
		this.kgUnitType = kgUnitType;
	}

	public KgCanton getKgcanton() {
		return kgcanton;
	}

	public void setKgcanton(KgCanton kgcanton) {
		this.kgcanton = kgcanton;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCantonid() {
		return cantonid;
	}

	public void setCantonid(Long cantonid) {
		this.cantonid = cantonid;
	}

	public String getUnitname() {
		return unitname;
	}

	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	public Long getUnittypeid() {
		return unittypeid;
	}

	public void setUnittypeid(Long unittypeid) {
		this.unittypeid = unittypeid;
	}

	public String getOffertitle() {
		return offertitle;
	}

	public void setOffertitle(String offertitle) {
		this.offertitle = offertitle;
	}

	public Integer getOffercount() {
		return offercount;
	}

	public void setOffercount(Integer offercount) {
		this.offercount = offercount;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getContactperson() {
		return contactperson;
	}

	public void setContactperson(String contactperson) {
		this.contactperson = contactperson;
	}

	public String getContactposition() {
		return contactposition;
	}

	public void setContactposition(String contactposition) {
		this.contactposition = contactposition;
	}

	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getContacttel() {
		return contacttel;
	}

	public void setContacttel(String contacttel) {
		this.contacttel = contacttel;
	}

	public Date getPublishdate() {
		return publishdate;
	}

	public void setPublishdate(Date publishdate) {
		this.publishdate = publishdate;
	}

	public String getNewsSimpleTitle() {
		return newsSimpleTitle;
	}

	public void setNewsSimpleTitle(String newsSimpleTitle) {
		this.newsSimpleTitle = newsSimpleTitle;
	}

	public Long getPublishuserid() {
		return publishuserid;
	}

	public void setPublishuserid(Long publishuserid) {
		this.publishuserid = publishuserid;
	}

   
     
     }
