package com.shtyxh.manager.dto;

import java.util.List;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "kg_questionmainitem")
public class KgQuestionmainitem extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_SID = "sid";
     public static final String FIELD_Q_ITEMS_TITLE = "qItemsTitle";
     public static final String FIELD_ITEM_TYPE = "itemType";


     @Id
     @GeneratedValue
     private Long id;

     @NotNull
     private Long sid;

     @NotEmpty
     @Length(max = 200)
     private String qItemsTitle;
     
     @Length(max = 200)
     private String analysis;

     @NotEmpty
     @Length(max = 200)
     private String itemType;

     @Transient
     private List<KgQuestionAnswer> qListItems;

     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setSid(Long sid){
         this.sid = sid;
     }

     public Long getSid(){
         return sid;
     }

     public void setItemType(String itemType){
         this.itemType = itemType;
     }

     public String getItemType(){
         return itemType;
     }

	public String getAnalysis() {
		return analysis;
	}

	public void setAnalysis(String analysis) {
		this.analysis = analysis;
	}

	public List<KgQuestionAnswer> getqListItems() {
		return qListItems;
	}

	public void setqListItems(List<KgQuestionAnswer> qListItems) {
		this.qListItems = qListItems;
	}

	public String getqItemsTitle() {
		return qItemsTitle;
	}

	public void setqItemsTitle(String qItemsTitle) {
		this.qItemsTitle = qItemsTitle;
	}
     
     

     }
