package com.shtyxh.manager.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "kg_unittype")
public class KgUnitType extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_UNITTYPENAME = "unittypename";


     @Id
     @GeneratedValue
     private String id;

     @Length(max = 255)
     private String unittypename;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setUnittypename(String unittypename){
         this.unittypename = unittypename;
     }

     public String getUnittypename(){
         return unittypename;
     }

     }
