package com.shtyxh.manager.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "kg_user_q_answer")
public class KgUserQAnswer extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_SID = "sid";
     public static final String FIELD_IP = "ip";
     public static final String FIELD_AID = "aid";
     public static final String FIELD_CHECKCURR = "checkcurr";
     public static final String FIELD_CONTENT = "content";


     @Id
     @GeneratedValue
     private Long id;
     
     @NotNull
     private Long sid;
     
     @Length(max = 40)
     private String ip;

     @NotNull
     private Long aid;
     
     private Boolean checkcurr;

     @Length(max = 65535)
     private String content;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     
     public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public void setAid(Long aid){
         this.aid = aid;
     }

     public Long getAid(){
         return aid;
     }

     public void setCheckcurr(Boolean checkcurr){
         this.checkcurr = checkcurr;
     }

     public Boolean getCheckcurr(){
         return checkcurr;
     }

     public void setContent(String content){
         this.content = content;
     }

     public String getContent(){
         return content;
     }

	public Long getSid() {
		return sid;
	}

	public void setSid(Long sid) {
		this.sid = sid;
	}
     

     }
