package com.shtyxh.manager.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "sys_role_func")
public class RoleFunc extends BaseDTO {

     public static final String FIELD_RF_ID = "rfId";
     public static final String FIELD_FUNC_ID = "funcId";
     public static final String FIELD_ROLE_ID = "roleId";


     @Id
     @GeneratedValue
     private Long rfId;

     private Long funcId;

     private Long roleId; //角色ID


     public void setRfId(Long rfId){
         this.rfId = rfId;
     }

     public Long getRfId(){
         return rfId;
     }

     public void setFuncId(Long funcId){
         this.funcId = funcId;
     }

     public Long getFuncId(){
         return funcId;
     }

     public void setRoleId(Long roleId){
         this.roleId = roleId;
     }

     public Long getRoleId(){
         return roleId;
     }

     }
