package com.shtyxh.manager.account.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.huan.HTed.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "sys_role")
public class Role extends BaseDTO {

     public static final String FIELD_ROLE_ID = "roleId";
     public static final String FIELD_ROLE_CODE = "roleCode";
     public static final String FIELD_ROLE_NAME = "roleName";
     public static final String FIELD_ROLE_DESCRIPTION = "roleDescription";


     @Id
     @GeneratedValue
     private Long roleId;

     @NotEmpty
     @Length(max = 40)
     private String roleCode; //角色编码

     @NotEmpty
     @Length(max = 150)
     private String roleName; //角色名称

     @Length(max = 240)
     private String roleDescription; //角色描述


     public void setRoleId(Long roleId){
         this.roleId = roleId;
     }

     public Long getRoleId(){
         return roleId;
     }

     public void setRoleCode(String roleCode){
         this.roleCode = roleCode;
     }

     public String getRoleCode(){
         return roleCode;
     }

     public void setRoleName(String roleName){
         this.roleName = roleName;
     }

     public String getRoleName(){
         return roleName;
     }

     public void setRoleDescription(String roleDescription){
         this.roleDescription = roleDescription;
     }

     public String getRoleDescription(){
         return roleDescription;
     }

     }
