package com.shtyxh.manager.account.dto;

/**Auto Generated By HTed Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.huan.HTed.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.huan.HTed.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "sys_user")
public class User extends BaseDTO {

     public static final String FIELD_USER_ID = "userId";
     public static final String FIELD_USER_TYPE = "userType";
     public static final String FIELD_USER_NAME = "userName";
     public static final String FIELD_PASSWORD_ENCRYPTED = "passwordEncrypted";
     public static final String FIELD_EMAIL = "email";
     public static final String FIELD_PHONE = "phone";
     public static final String FIELD_START_ACTIVE_DATE = "startActiveDate";
     public static final String FIELD_END_ACTIVE_DATE = "endActiveDate";
     public static final String FIELD_STATUS = "status";


     @Id
     @GeneratedValue
     private Long userId;

     @Length(max = 30)
     private String userType; //用户类型

     @NotEmpty
     @Length(max = 40)
     private String userName; //用户名
     
     @NotEmpty
     @Length(max = 40)
     private String realName; //用户名
     

     @Length(max = 80)
     private String passwordEncrypted; //加密过的密码
     
     @Transient
     private String newPasswordEncrypted; //用于修改密码

     @Length(max = 150)
     private String email; //邮箱地址

     @Length(max = 40)
     private String phone; //电话号码

     private Date startActiveDate; //有效期从

     private Date endActiveDate; //有效期至

     @Length(max = 30)
     private String status; //状态


     public String getNewPasswordEncrypted() {
		return newPasswordEncrypted;
	}

	public void setNewPasswordEncrypted(String newPasswordEncrypted) {
		this.newPasswordEncrypted = newPasswordEncrypted;
	}

	public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     public void setUserType(String userType){
         this.userType = userType;
     }

     public String getUserType(){
         return userType;
     }

     public void setUserName(String userName){
         this.userName = userName;
     }

     public String getUserName(){
         return userName;
     }

     public void setPasswordEncrypted(String passwordEncrypted){
         this.passwordEncrypted = passwordEncrypted;
     }

     public String getPasswordEncrypted(){
         return passwordEncrypted;
     }

     public void setEmail(String email){
         this.email = email;
     }

     public String getEmail(){
         return email;
     }

     public void setPhone(String phone){
         this.phone = phone;
     }

     public String getPhone(){
         return phone;
     }

     public void setStartActiveDate(Date startActiveDate){
         this.startActiveDate = startActiveDate;
     }

     public Date getStartActiveDate(){
         return startActiveDate;
     }

     public void setEndActiveDate(Date endActiveDate){
         this.endActiveDate = endActiveDate;
     }

     public Date getEndActiveDate(){
         return endActiveDate;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

     
     }
