/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.1.0.2.0

Source Server         : 192.168.17.104
Source Server Version : 110200
Source Host           : 192.168.17.104:1521
Source Schema         : HAP_DEV

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2019-05-09 14:22:19
*/


-- ----------------------------
-- Table structure for ZY_BORROW_APPLY
-- ----------------------------
DROP TABLE "ZY_BORROW_APPLY";
CREATE TABLE "ZY_BORROW_APPLY" (
"APPLY_NO" VARCHAR2(30 BYTE) NOT NULL ,
"APPLY_USERID" VARCHAR2(20 BYTE) NULL ,
"DOCUMENT_NUMBER" VARCHAR2(30 BYTE) NULL ,
"PZH" VARCHAR2(500 BYTE) NULL ,
"UNIT_CODE" VARCHAR2(20 BYTE) NULL ,
"ACCOUNTPERIOD_START" VARCHAR2(8 BYTE) NULL ,
"ACCOUNTPERIOD_END" VARCHAR2(8 BYTE) NULL ,
"USER_NAME" VARCHAR2(20 BYTE) NULL ,
"APPLY_DATETIME_START" VARCHAR2(8 BYTE) NULL ,
"APPLY_DATETIME_END" VARCHAR2(8 BYTE) NULL ,
"APPLY_REASON" VARCHAR2(500 BYTE) NULL ,
"APPLY_DATE" VARCHAR2(14 BYTE) NULL ,
"DOCUMENT_TYPEID" VARCHAR2(100 BYTE) NULL ,
"APPLY_UID" VARCHAR2(30 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ZY_BORROW_APPLY"."APPLY_NO" IS '申请单编号，自动生成，就是8位日期+6位时间+3位毫秒';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."APPLY_USERID" IS '申请单创建人';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."DOCUMENT_NUMBER" IS '单据编号';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."PZH" IS '凭证号，多个用逗号隔开';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."UNIT_CODE" IS '公司ID';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."ACCOUNTPERIOD_START" IS '会计期间开始';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."ACCOUNTPERIOD_END" IS '会计期间结束';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."USER_NAME" IS '查阅用户姓名';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."APPLY_DATETIME_START" IS '查询开始日期';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."APPLY_DATETIME_END" IS '查询结束日期';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."APPLY_REASON" IS '申请原因';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."APPLY_DATE" IS '申请时间，8位日期+6位时间';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."DOCUMENT_TYPEID" IS '单据类型，多个用逗号隔开';
COMMENT ON COLUMN "ZY_BORROW_APPLY"."APPLY_UID" IS '临时用户UID';

-- ----------------------------
-- Table structure for ZY_CACHEBACKINFO
-- ----------------------------
DROP TABLE "ZY_CACHEBACKINFO";
CREATE TABLE "ZY_CACHEBACKINFO" (
"PCID" VARCHAR2(30 BYTE) NULL ,
"CSGUID" VARCHAR2(50 BYTE) NULL ,
"CACHEIP" VARCHAR2(10 BYTE) NULL ,
"BKTIME" VARCHAR2(14 BYTE) NULL ,
"BKUSER" VARCHAR2(14 BYTE) NULL ,
"STATE" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_CONFIG
-- ----------------------------
DROP TABLE "ZY_CONFIG";
CREATE TABLE "ZY_CONFIG" (
"ID" NUMBER NOT NULL ,
"CONFIGNAME" VARCHAR2(255 BYTE) NULL ,
"CONFIGVALUE" VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_10076
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_10076";
CREATE TABLE "ZY_DEPTCACHEIMG_10076" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"IMGTYPE" VARCHAR2(20 BYTE) DEFAULT 99  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_10076_DEL
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_10076_DEL";
CREATE TABLE "ZY_DEPTCACHEIMG_10076_DEL" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_10078
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_10078";
CREATE TABLE "ZY_DEPTCACHEIMG_10078" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"IMGTYPE" VARCHAR2(20 BYTE) DEFAULT 99  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_101
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_101";
CREATE TABLE "ZY_DEPTCACHEIMG_101" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_101_DEL
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_101_DEL";
CREATE TABLE "ZY_DEPTCACHEIMG_101_DEL" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_DALL
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_DALL";
CREATE TABLE "ZY_DEPTCACHEIMG_DALL" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_DALL_DEL
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_DALL_DEL";
CREATE TABLE "ZY_DEPTCACHEIMG_DALL_DEL" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_HAND
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_HAND";
CREATE TABLE "ZY_DEPTCACHEIMG_HAND" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTCACHEIMG_HAND_DEL
-- ----------------------------
DROP TABLE "ZY_DEPTCACHEIMG_HAND_DEL";
CREATE TABLE "ZY_DEPTCACHEIMG_HAND_DEL" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(200 BYTE) NOT NULL ,
"PAGEID" NUMBER(10) NOT NULL ,
"COPYTIME" VARCHAR2(14 BYTE) NOT NULL ,
"TIMGPATH" VARCHAR2(200 BYTE) NULL ,
"IMGFILENAME" VARCHAR2(20 BYTE) NULL ,
"TIMGFILENAME" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DEPTEXT
-- ----------------------------
DROP TABLE "ZY_DEPTEXT";
CREATE TABLE "ZY_DEPTEXT" (
"DEPTID" VARCHAR2(32 BYTE) NOT NULL ,
"HCIP" VARCHAR2(32 BYTE) NULL ,
"HCPORT" VARCHAR2(32 BYTE) NULL ,
"HCUSER" VARCHAR2(20 BYTE) NULL ,
"HCPASS" VARCHAR2(20 BYTE) NULL ,
"DQUERYTOZB" NUMBER NULL ,
"LOCALPATH" VARCHAR2(2000 BYTE) NULL ,
"XNPATH" VARCHAR2(32 BYTE) NULL ,
"UPCASSIZE" NUMBER NULL ,
"TOMCATIP" VARCHAR2(32 BYTE) NULL ,
"TOMCATPORT" NUMBER NULL ,
"JKQUERYTIMEOUT" NUMBER NULL ,
"LOCALSCAN" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DOCUMENT_CATEGORY_WD
-- ----------------------------
DROP TABLE "ZY_DOCUMENT_CATEGORY_WD";
CREATE TABLE "ZY_DOCUMENT_CATEGORY_WD" (
"DOCUMENT_CATEGORY" VARCHAR2(100 BYTE) NOT NULL ,
"WDTYPEID" VARCHAR2(32 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DZWJ_BATCHXML
-- ----------------------------
DROP TABLE "ZY_DZWJ_BATCHXML";
CREATE TABLE "ZY_DZWJ_BATCHXML" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"BATCHXML" LONG NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DZWJ_BATCHXML_SSF
-- ----------------------------
DROP TABLE "ZY_DZWJ_BATCHXML_SSF";
CREATE TABLE "ZY_DZWJ_BATCHXML_SSF" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"BATCHXML" LONG NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DZWJINFO
-- ----------------------------
DROP TABLE "ZY_DZWJINFO";
CREATE TABLE "ZY_DZWJINFO" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"FILENAME" VARCHAR2(300 BYTE) NOT NULL ,
"IMGTYPE" VARCHAR2(50 BYTE) NULL ,
"FILEPATH" VARCHAR2(500 BYTE) NULL ,
"ID" NUMBER NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DZWJINFO_DEL
-- ----------------------------
DROP TABLE "ZY_DZWJINFO_DEL";
CREATE TABLE "ZY_DZWJINFO_DEL" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"FILENAME" VARCHAR2(300 BYTE) NOT NULL ,
"IMGTYPE" VARCHAR2(50 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DZWJINFO_DEL_SSF
-- ----------------------------
DROP TABLE "ZY_DZWJINFO_DEL_SSF";
CREATE TABLE "ZY_DZWJINFO_DEL_SSF" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"FILENAME" VARCHAR2(300 BYTE) NOT NULL ,
"IMGTYPE" VARCHAR2(50 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DZWJINFO_SSF
-- ----------------------------
DROP TABLE "ZY_DZWJINFO_SSF";
CREATE TABLE "ZY_DZWJINFO_SSF" (
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"FILENAME" VARCHAR2(300 BYTE) NOT NULL ,
"IMGTYPE" VARCHAR2(50 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_DZWJLOG
-- ----------------------------
DROP TABLE "ZY_DZWJLOG";
CREATE TABLE "ZY_DZWJLOG" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"OPERUSER" VARCHAR2(50 BYTE) NOT NULL ,
"OPER" VARCHAR2(2 BYTE) NOT NULL ,
"OPERFILE" VARCHAR2(500 BYTE) NOT NULL ,
"CLIENTIP" VARCHAR2(20 BYTE) NULL ,
"OPERDATE" VARCHAR2(30 BYTE) NOT NULL ,
"OPEROLDFILE" VARCHAR2(500 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_IMGPZ
-- ----------------------------
DROP TABLE "ZY_IMGPZ";
CREATE TABLE "ZY_IMGPZ" (
"GUID" VARCHAR2(200 BYTE) NOT NULL ,
"PZXML" VARCHAR2(4000 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_KEY_DEPTCATCHTABLE
-- ----------------------------
DROP TABLE "ZY_KEY_DEPTCATCHTABLE";
CREATE TABLE "ZY_KEY_DEPTCATCHTABLE" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"TABLENAME" VARCHAR2(50 BYTE) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_KEY_DEPTCATCHTABLE_DEL
-- ----------------------------
DROP TABLE "ZY_KEY_DEPTCATCHTABLE_DEL";
CREATE TABLE "ZY_KEY_DEPTCATCHTABLE_DEL" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"TABLENAME" VARCHAR2(50 BYTE) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_KEY_DEPTCATCHTABLE_DEL_SSF
-- ----------------------------
DROP TABLE "ZY_KEY_DEPTCATCHTABLE_DEL_SSF";
CREATE TABLE "ZY_KEY_DEPTCATCHTABLE_DEL_SSF" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"TABLENAME" VARCHAR2(50 BYTE) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_KEY_DEPTCATCHTABLE_SSF
-- ----------------------------
DROP TABLE "ZY_KEY_DEPTCATCHTABLE_SSF";
CREATE TABLE "ZY_KEY_DEPTCATCHTABLE_SSF" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"TABLENAME" VARCHAR2(50 BYTE) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_KEY_DZWJINFO
-- ----------------------------
DROP TABLE "ZY_KEY_DZWJINFO";
CREATE TABLE "ZY_KEY_DZWJINFO" (
"BARCODE" VARCHAR2(50 BYTE) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"FILESAVEPATH" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_RESCANSTATE
-- ----------------------------
DROP TABLE "ZY_RESCANSTATE";
CREATE TABLE "ZY_RESCANSTATE" (
"SEQNO" VARCHAR2(50 BYTE) NULL ,
"DOCUMENT_SOURCE" VARCHAR2(10 BYTE) NULL ,
"DOCUMENT_NUMBER" VARCHAR2(30 BYTE) NULL ,
"EMPLOYEE_CODE" VARCHAR2(30 BYTE) NULL ,
"UNIT_CODE" VARCHAR2(30 BYTE) NULL ,
"SCANMSG" VARCHAR2(500 BYTE) NULL ,
"SCANSTATE" NUMBER NULL ,
"FMSG" VARCHAR2(2000 BYTE) NULL ,
"CREATEDT" CHAR(14 BYTE) NULL ,
"FANISHDT" CHAR(14 BYTE) NULL ,
"SCANUSERID" VARCHAR2(20 BYTE) NULL ,
"SCANDEPT" VARCHAR2(20 BYTE) NULL ,
"TZDATE" CHAR(14 BYTE) NULL ,
"STATE" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ZY_RESCANSTATE"."SEQNO" IS '流水号';
COMMENT ON COLUMN "ZY_RESCANSTATE"."DOCUMENT_SOURCE" IS '业务来源代码';
COMMENT ON COLUMN "ZY_RESCANSTATE"."DOCUMENT_NUMBER" IS '单据号';
COMMENT ON COLUMN "ZY_RESCANSTATE"."EMPLOYEE_CODE" IS '重扫用户所在业务系统的用户ID';
COMMENT ON COLUMN "ZY_RESCANSTATE"."UNIT_CODE" IS '重扫用户所在业务系统的部门ID';
COMMENT ON COLUMN "ZY_RESCANSTATE"."SCANMSG" IS '业务系统发送过来的重扫原因';
COMMENT ON COLUMN "ZY_RESCANSTATE"."SCANSTATE" IS '0-重扫，1-补扫已完成，10-通知失败';
COMMENT ON COLUMN "ZY_RESCANSTATE"."FMSG" IS '通知失败原因';
COMMENT ON COLUMN "ZY_RESCANSTATE"."CREATEDT" IS '重扫任务创建时间';
COMMENT ON COLUMN "ZY_RESCANSTATE"."FANISHDT" IS '重扫完成时间';
COMMENT ON COLUMN "ZY_RESCANSTATE"."SCANUSERID" IS '重扫用户，影像系统用户';
COMMENT ON COLUMN "ZY_RESCANSTATE"."SCANDEPT" IS '重扫部门，扫描用户所在部门';
COMMENT ON COLUMN "ZY_RESCANSTATE"."TZDATE" IS '通知时间';
COMMENT ON COLUMN "ZY_RESCANSTATE"."STATE" IS '1-重扫，0-退单';

-- ----------------------------
-- Table structure for ZY_TASKINSTANCE
-- ----------------------------
DROP TABLE "ZY_TASKINSTANCE";
CREATE TABLE "ZY_TASKINSTANCE" (
"INSTANCEID" NUMBER(10) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(100 BYTE) NOT NULL ,
"STATE" NUMBER DEFAULT 0  NOT NULL ,
"DEPTID" VARCHAR2(50 BYTE) NULL ,
"USERID" VARCHAR2(50 BYTE) NOT NULL ,
"UPTIME" CHAR(14 BYTE) NULL ,
"UPLOCALIP" VARCHAR2(15 BYTE) NULL ,
"CFLSIMGTIME" CHAR(14 BYTE) NULL ,
"ILSTIME" CHAR(14 BYTE) NULL ,
"CACHEIP" VARCHAR2(15 BYTE) NOT NULL ,
"ERRDESC" VARCHAR2(4000 BYTE) NULL ,
"LOCALPATH" VARCHAR2(50 BYTE) NOT NULL ,
"FTYPE" NUMBER DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_TASKINSTANCE_DEL
-- ----------------------------
DROP TABLE "ZY_TASKINSTANCE_DEL";
CREATE TABLE "ZY_TASKINSTANCE_DEL" (
"INSTANCEID" NUMBER(10) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(100 BYTE) NOT NULL ,
"STATE" NUMBER DEFAULT 0  NOT NULL ,
"DEPTID" VARCHAR2(50 BYTE) NULL ,
"USERID" VARCHAR2(50 BYTE) NOT NULL ,
"UPTIME" CHAR(14 BYTE) NULL ,
"UPLOCALIP" VARCHAR2(15 BYTE) NULL ,
"CFLSIMGTIME" CHAR(14 BYTE) NULL ,
"ILSTIME" CHAR(14 BYTE) NULL ,
"CACHEIP" VARCHAR2(15 BYTE) NOT NULL ,
"ERRDESC" VARCHAR2(4000 BYTE) NULL ,
"LOCALPATH" VARCHAR2(50 BYTE) NOT NULL ,
"FTYPE" NUMBER DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_TASKINSTANCE_DEL_SSF
-- ----------------------------
DROP TABLE "ZY_TASKINSTANCE_DEL_SSF";
CREATE TABLE "ZY_TASKINSTANCE_DEL_SSF" (
"INSTANCEID" NUMBER(10) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(100 BYTE) NOT NULL ,
"STATE" NUMBER DEFAULT 0  NOT NULL ,
"DEPTID" VARCHAR2(50 BYTE) NULL ,
"USERID" VARCHAR2(50 BYTE) NOT NULL ,
"UPTIME" CHAR(14 BYTE) NULL ,
"UPLOCALIP" VARCHAR2(15 BYTE) NULL ,
"CFLSIMGTIME" CHAR(14 BYTE) NULL ,
"ILSTIME" CHAR(14 BYTE) NULL ,
"CACHEIP" VARCHAR2(15 BYTE) NOT NULL ,
"ERRDESC" VARCHAR2(4000 BYTE) NULL ,
"LOCALPATH" VARCHAR2(50 BYTE) NOT NULL ,
"FTYPE" NUMBER DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_TASKINSTANCE_SSF
-- ----------------------------
DROP TABLE "ZY_TASKINSTANCE_SSF";
CREATE TABLE "ZY_TASKINSTANCE_SSF" (
"INSTANCEID" NUMBER(10) NOT NULL ,
"CSGUID" VARCHAR2(50 BYTE) NOT NULL ,
"IMGPATH" VARCHAR2(100 BYTE) NOT NULL ,
"STATE" NUMBER DEFAULT 0  NOT NULL ,
"DEPTID" VARCHAR2(50 BYTE) NULL ,
"USERID" VARCHAR2(50 BYTE) NOT NULL ,
"UPTIME" CHAR(14 BYTE) NULL ,
"UPLOCALIP" VARCHAR2(15 BYTE) NULL ,
"CFLSIMGTIME" CHAR(14 BYTE) NULL ,
"ILSTIME" CHAR(14 BYTE) NULL ,
"CACHEIP" VARCHAR2(15 BYTE) NOT NULL ,
"ERRDESC" VARCHAR2(4000 BYTE) NULL ,
"LOCALPATH" VARCHAR2(50 BYTE) NOT NULL ,
"FTYPE" NUMBER DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_TEST_JIEKOU
-- ----------------------------
DROP TABLE "ZY_TEST_JIEKOU";
CREATE TABLE "ZY_TEST_JIEKOU" (
"SEQID" VARCHAR2(50 BYTE) NULL ,
"BARCODE" VARCHAR2(50 BYTE) NULL ,
"USERID" VARCHAR2(50 BYTE) NULL ,
"DEPTID" VARCHAR2(50 BYTE) NULL ,
"TYPEID" VARCHAR2(50 BYTE) NULL ,
"CLIENTIP" VARCHAR2(50 BYTE) NULL ,
"SERVERDT" NUMBER NULL ,
"DOCUMENT_SOURCE" VARCHAR2(10 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for ZY_TEST_YWINFO
-- ----------------------------
DROP TABLE "ZY_TEST_YWINFO";
CREATE TABLE "ZY_TEST_YWINFO" (
"COMPANY_CODE" VARCHAR2(30 BYTE) NULL ,
"COMPANY_SHORT_NAME" VARCHAR2(1000 BYTE) NULL ,
"DOCUMENT_CATEGORY" VARCHAR2(30 BYTE) NULL ,
"DOCUMENT_NUMBER" VARCHAR2(30 BYTE) NULL ,
"EMPLOYEE_CODE" VARCHAR2(30 BYTE) NULL ,
"EMPLOYEE_NAME" VARCHAR2(50 BYTE) NULL ,
"UNIT_CODE" VARCHAR2(30 BYTE) NULL ,
"UNIT_DESCRIPTION" VARCHAR2(1000 BYTE) NULL ,
"DOCUMENT_TYPE_CODE" VARCHAR2(30 BYTE) NULL ,
"DOCUMENT_TYPE_DESC" VARCHAR2(1000 BYTE) NULL ,
"STATUS" VARCHAR2(30 BYTE) DEFAULT 'GENERAL'  NULL ,
"AMOUNT" NUMBER NULL ,
"DOCUMENT_SOURCE" VARCHAR2(10 BYTE) NULL ,
"SCANUSERID" VARCHAR2(20 BYTE) NULL ,
"SCANDEPT" VARCHAR2(20 BYTE) NULL ,
"SCANDATE" CHAR(14 BYTE) NULL ,
"SCANSTATE" NUMBER NULL ,
"FMSG" VARCHAR2(2000 BYTE) NULL ,
"TZDATE" CHAR(14 BYTE) NULL ,
"DOCUMENT_DATE" DATE NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ZY_TEST_YWINFO"."SCANDATE" IS '扫描完成时间';
COMMENT ON COLUMN "ZY_TEST_YWINFO"."SCANSTATE" IS '10为通知失败,1为通知成功';
COMMENT ON COLUMN "ZY_TEST_YWINFO"."FMSG" IS '通知失败原因';
COMMENT ON COLUMN "ZY_TEST_YWINFO"."TZDATE" IS '通知时间';

-- ----------------------------
-- Table structure for ZY_ZXDATABACKINFO
-- ----------------------------
DROP TABLE "ZY_ZXDATABACKINFO";
CREATE TABLE "ZY_ZXDATABACKINFO" (
"BKVT" VARCHAR2(10 BYTE) NULL ,
"BKDT" VARCHAR2(10 BYTE) NULL ,
"BKVTIDX" NUMBER NULL ,
"BKDTIDX" NUMBER NULL ,
"BKLOCALPATH" VARCHAR2(200 BYTE) NULL ,
"BKTIME" VARCHAR2(14 BYTE) NULL ,
"BKUSER" VARCHAR2(14 BYTE) NULL ,
"STATE" NUMBER NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Sequence structure for ZY_CONFIG_S
-- ----------------------------
DROP SEQUENCE "ZY_CONFIG_S";
CREATE SEQUENCE "ZY_CONFIG_S"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 10001
 CACHE 29;

-- ----------------------------
-- Sequence structure for ZY_DZWJINFO_S
-- ----------------------------
DROP SEQUENCE "ZY_DZWJINFO_S";
CREATE SEQUENCE "ZY_DZWJINFO_S"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 10041
 CACHE 20;

-- ----------------------------
-- Sequence structure for ZY_TASKINSTANCE_S
-- ----------------------------
DROP SEQUENCE "ZY_TASKINSTANCE_S";
CREATE SEQUENCE "ZY_TASKINSTANCE_S"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999999999999999999999999
 START WITH 1762
 CACHE 20;

-- ----------------------------
-- Sequence structure for ZY_TASKINSTANCE_SSF_SEQ
-- ----------------------------
DROP SEQUENCE "ZY_TASKINSTANCE_SSF_SEQ";
CREATE SEQUENCE "ZY_TASKINSTANCE_SSF_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999999999999999999999999
 START WITH 174880
 CACHE 20;

-- ----------------------------
-- Sequence structure for ZY_TEST_JIEKOU_SEQ
-- ----------------------------
DROP SEQUENCE "ZY_TEST_JIEKOU_SEQ";
CREATE SEQUENCE "ZY_TEST_JIEKOU_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999999999999999999999999
 START WITH 260
 CACHE 20;

-- ----------------------------
-- Indexes structure for table ZY_BORROW_APPLY
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZY_BORROW_APPLY
-- ----------------------------
ALTER TABLE "ZY_BORROW_APPLY" ADD CHECK ("APPLY_NO" IS NOT NULL);
ALTER TABLE "ZY_BORROW_APPLY" ADD CHECK ("APPLY_NO" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_BORROW_APPLY
-- ----------------------------
ALTER TABLE "ZY_BORROW_APPLY" ADD PRIMARY KEY ("APPLY_NO");

-- ----------------------------
-- Indexes structure for table ZY_CACHEBACKINFO
-- ----------------------------
CREATE UNIQUE INDEX "PK_ZY_CACHEBACKINFO"
ON "ZY_CACHEBACKINFO" ("PCID" ASC, "CSGUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Indexes structure for table ZY_CONFIG
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZY_CONFIG
-- ----------------------------
ALTER TABLE "ZY_CONFIG" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_CONFIG
-- ----------------------------
ALTER TABLE "ZY_CONFIG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_10076
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_10076_DEL
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10076_DEL" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_10078
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_10078" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_DEPTCACHEIMG_101
-- ----------------------------
CREATE INDEX "IX_ZY_DEPTCACHEIMG_101_BAR"
ON "ZY_DEPTCACHEIMG_101" ("BARCODE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_DEPTCACHEIMG_101_CSGUID"
ON "ZY_DEPTCACHEIMG_101" ("CSGUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_101
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_101_DEL
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_101_DEL" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_DEPTCACHEIMG_DALL
-- ----------------------------
CREATE INDEX "IX_ZY_DEPTCACHEIMG_DALL_BAR"
ON "ZY_DEPTCACHEIMG_DALL" ("BARCODE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_DEPTCACHEIMG_DALL_CSGUID"
ON "ZY_DEPTCACHEIMG_DALL" ("CSGUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_DALL
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_DALL_DEL
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_DALL_DEL" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_DEPTCACHEIMG_HAND
-- ----------------------------
CREATE INDEX "IX_ZY_DEPTCACHEIMG_HAND_BAR"
ON "ZY_DEPTCACHEIMG_HAND" ("BARCODE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_DEPTCACHEIMG_HAND_CSGUID"
ON "ZY_DEPTCACHEIMG_HAND" ("CSGUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_HAND
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Checks structure for table ZY_DEPTCACHEIMG_HAND_DEL
-- ----------------------------
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("COPYTIME" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("PAGEID" IS NOT NULL);
ALTER TABLE "ZY_DEPTCACHEIMG_HAND_DEL" ADD CHECK ("COPYTIME" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_DEPTEXT
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZY_DEPTEXT
-- ----------------------------
ALTER TABLE "ZY_DEPTEXT" ADD CHECK ("DEPTID" IS NOT NULL);
ALTER TABLE "ZY_DEPTEXT" ADD CHECK ("DEPTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_DEPTEXT
-- ----------------------------
ALTER TABLE "ZY_DEPTEXT" ADD PRIMARY KEY ("DEPTID");

-- ----------------------------
-- Indexes structure for table ZY_DOCUMENT_CATEGORY_WD
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZY_DOCUMENT_CATEGORY_WD
-- ----------------------------
ALTER TABLE "ZY_DOCUMENT_CATEGORY_WD" ADD CHECK ("DOCUMENT_CATEGORY" IS NOT NULL);
ALTER TABLE "ZY_DOCUMENT_CATEGORY_WD" ADD CHECK ("WDTYPEID" IS NOT NULL);
ALTER TABLE "ZY_DOCUMENT_CATEGORY_WD" ADD CHECK ("DOCUMENT_CATEGORY" IS NOT NULL);
ALTER TABLE "ZY_DOCUMENT_CATEGORY_WD" ADD CHECK ("WDTYPEID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_DOCUMENT_CATEGORY_WD
-- ----------------------------
ALTER TABLE "ZY_DOCUMENT_CATEGORY_WD" ADD PRIMARY KEY ("DOCUMENT_CATEGORY");

-- ----------------------------
-- Indexes structure for table ZY_DZWJ_BATCHXML
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZY_DZWJ_BATCHXML
-- ----------------------------
ALTER TABLE "ZY_DZWJ_BATCHXML" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJ_BATCHXML" ADD CHECK ("BATCHXML" IS NOT NULL);
ALTER TABLE "ZY_DZWJ_BATCHXML" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJ_BATCHXML" ADD CHECK ("BATCHXML" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_DZWJ_BATCHXML
-- ----------------------------
ALTER TABLE "ZY_DZWJ_BATCHXML" ADD PRIMARY KEY ("BARCODE");

-- ----------------------------
-- Indexes structure for table ZY_DZWJ_BATCHXML_SSF
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZY_DZWJ_BATCHXML_SSF
-- ----------------------------
ALTER TABLE "ZY_DZWJ_BATCHXML_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJ_BATCHXML_SSF" ADD CHECK ("BATCHXML" IS NOT NULL);
ALTER TABLE "ZY_DZWJ_BATCHXML_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJ_BATCHXML_SSF" ADD CHECK ("BATCHXML" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_DZWJ_BATCHXML_SSF
-- ----------------------------
ALTER TABLE "ZY_DZWJ_BATCHXML_SSF" ADD PRIMARY KEY ("BARCODE");

-- ----------------------------
-- Indexes structure for table ZY_DZWJINFO
-- ----------------------------
CREATE UNIQUE INDEX "IX_ZY_DZWJINFO_FILENAME"
ON "ZY_DZWJINFO" ("FILENAME" ASC, "BARCODE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_DZWJINFO
-- ----------------------------
ALTER TABLE "ZY_DZWJINFO" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_DZWJINFO
-- ----------------------------
ALTER TABLE "ZY_DZWJINFO" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table ZY_DZWJINFO_DEL
-- ----------------------------
ALTER TABLE "ZY_DZWJINFO_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL" ADD CHECK ("FILENAME" IS NOT NULL);

-- ----------------------------
-- Checks structure for table ZY_DZWJINFO_DEL_SSF
-- ----------------------------
ALTER TABLE "ZY_DZWJINFO_DEL_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL_SSF" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_DEL_SSF" ADD CHECK ("FILENAME" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_DZWJINFO_SSF
-- ----------------------------
CREATE INDEX "IX_ZY_DZWJINFO_BARCODE_SSF"
ON "ZY_DZWJINFO_SSF" ("BARCODE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_DZWJINFO_CSGUID_SSF"
ON "ZY_DZWJINFO_SSF" ("CSGUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_DZWJINFO_SSF
-- ----------------------------
ALTER TABLE "ZY_DZWJINFO_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_SSF" ADD CHECK ("FILENAME" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJINFO_SSF" ADD CHECK ("FILENAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_DZWJINFO_SSF
-- ----------------------------
ALTER TABLE "ZY_DZWJINFO_SSF" ADD PRIMARY KEY ("CSGUID", "BARCODE", "FILENAME");

-- ----------------------------
-- Indexes structure for table ZY_DZWJLOG
-- ----------------------------
CREATE INDEX "IX_ZY_DZWJLOG_BARCODECODE"
ON "ZY_DZWJLOG" ("BARCODE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_DZWJLOG
-- ----------------------------
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("OPERUSER" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("OPER" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("OPERFILE" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("OPERDATE" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("OPERUSER" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("OPER" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("OPERFILE" IS NOT NULL);
ALTER TABLE "ZY_DZWJLOG" ADD CHECK ("OPERDATE" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_IMGPZ
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZY_IMGPZ
-- ----------------------------
ALTER TABLE "ZY_IMGPZ" ADD CHECK ("GUID" IS NOT NULL);
ALTER TABLE "ZY_IMGPZ" ADD CHECK ("GUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_IMGPZ
-- ----------------------------
ALTER TABLE "ZY_IMGPZ" ADD PRIMARY KEY ("GUID");

-- ----------------------------
-- Indexes structure for table ZY_KEY_DEPTCATCHTABLE
-- ----------------------------
CREATE INDEX "IX_KEY_DEPTCATCHTABLE_CSGUID"
ON "ZY_KEY_DEPTCATCHTABLE" ("CSGUID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_KEY_DEPTCATCHTABLE_BAR"
ON "ZY_KEY_DEPTCATCHTABLE" ("BARCODE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_KEY_DEPTCATCHTABLE
-- ----------------------------
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE" ADD CHECK ("TABLENAME" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE" ADD CHECK ("TABLENAME" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE" ADD CHECK ("CSGUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_KEY_DEPTCATCHTABLE
-- ----------------------------
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE" ADD PRIMARY KEY ("BARCODE");

-- ----------------------------
-- Indexes structure for table ZY_KEY_DEPTCATCHTABLE_DEL
-- ----------------------------
CREATE INDEX "IX_KEY_CATCHTABLE_DEL_CSGUID"
ON "ZY_KEY_DEPTCATCHTABLE_DEL" ("CSGUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_KEY_DEPTCATCHTABLE_DEL
-- ----------------------------
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL" ADD CHECK ("TABLENAME" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL" ADD CHECK ("TABLENAME" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL" ADD CHECK ("CSGUID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_KEY_DEPTCATCHTABLE_DEL_SSF
-- ----------------------------
CREATE INDEX "IX_KEY_CATCHTABLE_DEL_CSGUID_S"
ON "ZY_KEY_DEPTCATCHTABLE_DEL_SSF" ("CSGUID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_KEY_DEPTCATCHTABLE_DEL_SSF
-- ----------------------------
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL_SSF" ADD CHECK ("TABLENAME" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL_SSF" ADD CHECK ("TABLENAME" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_DEL_SSF" ADD CHECK ("CSGUID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_KEY_DEPTCATCHTABLE_SSF
-- ----------------------------
CREATE INDEX "IX_KEY_DEPTCATCHTABLE_CSGUID_S"
ON "ZY_KEY_DEPTCATCHTABLE_SSF" ("CSGUID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_KEY_DEPTCATCHTABLE_BAR_S"
ON "ZY_KEY_DEPTCATCHTABLE_SSF" ("BARCODE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_KEY_DEPTCATCHTABLE_SSF
-- ----------------------------
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_SSF" ADD CHECK ("TABLENAME" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_SSF" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_SSF" ADD CHECK ("TABLENAME" IS NOT NULL);
ALTER TABLE "ZY_KEY_DEPTCATCHTABLE_SSF" ADD CHECK ("CSGUID" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_KEY_DZWJINFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZY_KEY_DZWJINFO
-- ----------------------------
ALTER TABLE "ZY_KEY_DZWJINFO" ADD CHECK ("BARCODE" IS NOT NULL);
ALTER TABLE "ZY_KEY_DZWJINFO" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_KEY_DZWJINFO" ADD CHECK ("FILESAVEPATH" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_KEY_DZWJINFO
-- ----------------------------
ALTER TABLE "ZY_KEY_DZWJINFO" ADD PRIMARY KEY ("BARCODE");

-- ----------------------------
-- Indexes structure for table ZY_TASKINSTANCE
-- ----------------------------
CREATE INDEX "IX_ZY_TASKINSTANCE_CACHEIP"
ON "ZY_TASKINSTANCE" ("CACHEIP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_TASKINSTANCE_CSGUID"
ON "ZY_TASKINSTANCE" ("CSGUID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_TASKINSTANCE_DEPTID"
ON "ZY_TASKINSTANCE" ("DEPTID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_TASKINSTANCE_USERID"
ON "ZY_TASKINSTANCE" ("USERID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Triggers structure for table ZY_TASKINSTANCE
-- ----------------------------
CREATE OR REPLACE TRIGGER "TRG_ZY_TASKINSTANCE_S" BEFORE INSERT ON "ZY_TASKINSTANCE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
BEGIN 
  SELECT ZY_TASKINSTANCE_S.NEXTVAL INTO :NEW.INSTANCEID FROM DUAL; 
END;
-- ----------------------------
-- Checks structure for table ZY_TASKINSTANCE
-- ----------------------------
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("INSTANCEID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("CACHEIP" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("LOCALPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("INSTANCEID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("CACHEIP" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE" ADD CHECK ("LOCALPATH" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_TASKINSTANCE
-- ----------------------------
ALTER TABLE "ZY_TASKINSTANCE" ADD PRIMARY KEY ("INSTANCEID");

-- ----------------------------
-- Checks structure for table ZY_TASKINSTANCE_DEL
-- ----------------------------
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("INSTANCEID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("CACHEIP" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("LOCALPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("INSTANCEID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("CACHEIP" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL" ADD CHECK ("LOCALPATH" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_TASKINSTANCE_DEL_SSF
-- ----------------------------
CREATE INDEX "IX_ZY_TASKINSTANCE_CACHEIP_DEL"
ON "ZY_TASKINSTANCE_DEL_SSF" ("CACHEIP" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ZY_TASKINSTANCE_DEL_SSF
-- ----------------------------
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("INSTANCEID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("CACHEIP" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("LOCALPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("INSTANCEID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("CACHEIP" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_DEL_SSF" ADD CHECK ("LOCALPATH" IS NOT NULL);

-- ----------------------------
-- Indexes structure for table ZY_TASKINSTANCE_SSF
-- ----------------------------
CREATE INDEX "IX_ZY_TASKINSTANCE_SSF_CACHEIP"
ON "ZY_TASKINSTANCE_SSF" ("CACHEIP" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_TASKINSTANCE_SSF_CSGUID"
ON "ZY_TASKINSTANCE_SSF" ("CSGUID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_TASKINSTANCE_SSF_DEPTID"
ON "ZY_TASKINSTANCE_SSF" ("DEPTID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IX_ZY_TASKINSTANCE_SSF_USERID"
ON "ZY_TASKINSTANCE_SSF" ("USERID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Triggers structure for table ZY_TASKINSTANCE_SSF
-- ----------------------------
CREATE OR REPLACE TRIGGER "TRG_ZY_TASKINSTANCE_SSF_SEQ" BEFORE INSERT ON "ZY_TASKINSTANCE_SSF" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
BEGIN
  SELECT ZY_TASKINSTANCE_SSF_SEQ.NEXTVAL INTO :NEW.INSTANCEID FROM DUAL;
END;
-- ----------------------------
-- Checks structure for table ZY_TASKINSTANCE_SSF
-- ----------------------------
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("INSTANCEID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("CACHEIP" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("LOCALPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("INSTANCEID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("CSGUID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("IMGPATH" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("STATE" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("CACHEIP" IS NOT NULL);
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD CHECK ("LOCALPATH" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZY_TASKINSTANCE_SSF
-- ----------------------------
ALTER TABLE "ZY_TASKINSTANCE_SSF" ADD PRIMARY KEY ("INSTANCEID");

-- ----------------------------
-- Triggers structure for table ZY_TEST_JIEKOU
-- ----------------------------
CREATE OR REPLACE TRIGGER "TRG_ZY_TEST_JIEKOU_SEQ" BEFORE INSERT ON "ZY_TEST_JIEKOU" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW ENABLE
BEGIN
  SELECT ZY_TEST_JIEKOU_SEQ.NEXTVAL INTO :NEW.SEQID FROM DUAL;
END;
-- ----------------------------
-- Indexes structure for table ZY_ZXDATABACKINFO
-- ----------------------------
CREATE UNIQUE INDEX "PK_ZY_ZXDATABACKINFO"
ON "ZY_ZXDATABACKINFO" ("BKVT" ASC, "BKDT" ASC, "BKVTIDX" ASC, "BKDTIDX" ASC)
LOGGING
VISIBLE;
